# Generated by Django 4.2.16 on 2024-09-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('discount', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('in_stock', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('price_code', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('short_description', models.CharField(max_length=255)),
                ('sold_quantity', models.IntegerField(default=0)),
                ('brand_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
