# Generated by Django 4.2.16 on 2024-09-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_roles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
